### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by ArthurFuchsReis** [Kamilahsantos/Client-Angular-Live-Coding-Dio#1]
Boa Tarde kamila, tudo bem?

Estou aprendendo Angular do zero pelo youtube, mas estou sentindo dificuldade.

Tem algum material bom que a senhora pode me indicar, por favor.

Att,

@ArthurFuchsReis

**Comment by luisangelorjr** [comment]
@ArthurFuchsReis , eu indicaria os cursos da Loiane.
Vou começar essa semana a estuda-los nesse link:
https://loiane.training/curso/angular

Já trampei na mesma equipe de fronts Angular que só elogiavam o curso dela

@Kamilahsantos , o que acha?

**Comment by ArthurFuchsReis** [comment]
Obrigado

**Comment by Kamilahsantos** [comment]
Isso mesmo, loiane é uma das melhores referencias no assunto, esse curso é excelente
